### ISSUE TITLE
API for create ride should not take an input parameter

### ISSUE THREAD

**Issue by WillDignazio** [liam-middlebrook/open-container#12]
The user provides their own number for a ride, which currently will yield a 500 if you provide a number that already has been used. Users can also provide negative numbers, zero, and values beyond MAX_$type. 

You probably want to do away with providing an input `/create/ride/X` endpoint, and maintain a strictly increasing value server side.

**Comment by liam-middlebrook** [comment]
The `/create/ride/<x>` endpoint takes a parameter `x` that is actually the eventId to create the ride for. The actual code for creating a ride on the backend does automatically increment the rideIDs on server side.

This is a low-priority issue where the fix just prevents the 500.

**Comment by WillDignazio** [comment]
Ah gotcha, thx.
